FROM node:20-slim
WORKDIR /app
COPY ["orelens 2/frontend/", "/app/"]
ARG NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
RUN npm install && npm run build
EXPOSE 3000
CMD ["npm", "start"]

